"""empty message

Revision ID: 1966bb9cbe01
Revises: 71064c85c211
Create Date: 2021-03-17 12:07:21.443844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1966bb9cbe01'
down_revision = '71064c85c211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'date')
    # ### end Alembic commands ###
